package main

import (
	"flag"
	"fmt"
	"os"
	"runtime"
	"slices"

	gohpts "github.com/shadowy-pycoder/go-http-proxy-to-socks"
	"github.com/shadowy-pycoder/mshark/network"
	"golang.org/x/term"
)

const (
	app       string = "gohpts"
	addrSOCKS string = "127.0.0.1:1080"
	addrHTTP  string = "127.0.0.1:8080"
)

const usagePrefix string = `   _____       _    _ _____ _______ _____
  / ____|     | |  | |  __ \__   __/ ____|
 | |  __  ___ | |__| | |__) | | | | (___
 | | |_ |/ _ \|  __  |  ___/  | |  \___ \
 | |__| | (_) | |  | | |      | |  ____) |
  \_____|\___/|_|  |_|_|      |_| |_____/

GoHPTS (HTTP(S) Proxy to SOCKS5 proxy) by shadowy-pycoder
GitHub: https://github.com/shadowy-pycoder/go-http-proxy-to-socks

Usage: gohpts [OPTIONS]
OPTIONS:
  General:
  -h        Show this help message and exit
  -v        Show version and build information
  -D        Run as a daemon (provide -logfile to see logs)
  -I        Display list of network interfaces and exit

  Proxy:
  -l        Address of HTTP proxy server (Default: "127.0.0.1:8080")
  -s        Address of SOCKS5 proxy server (Default: "127.0.0.1:1080")
  -c        Path to certificate PEM encoded file
  -k        Path to private key PEM encoded file
  -U        User for HTTP proxy (basic auth). This flag invokes prompt for password (not echoed to terminal)
  -u        User for SOCKS5 proxy authentication. This flag invokes prompt for password (not echoed to terminal)
  -i        Bind proxy to specific network interface (either by interface name or index)
  -f        Path to server configuration file in YAML format (overrides proxy flags above)
  -6        Enable IPv6 support for TCP and UDP

  Logs:
  -d        Show logs in DEBUG mode
  -j        Show logs in JSON format
  -logfile  Log file path (Default: stdout)
  -nocolor  Disable colored output for logs (no effect if -j flag specified)
  -pprof    Address of pprof server with profiling data

  Sniffing:
  -sniff    Enable traffic sniffing for HTTP and TLS
  -snifflog Sniffed traffic log file path (Default: the same as -logfile)
  -body     Collect request and response body for HTTP traffic (credentials, tokens, etc)
`

const usageTproxy string = `
  TProxy:
  -t        Address of transparent proxy server (it starts along with HTTP proxy server)
  -T        Address of transparent proxy server (no HTTP)
  -Tu       Address of transparent UDP proxy server
  -M        Transparent proxy mode: (redirect, tproxy)
  -w        Number of instances of transparent proxy server (Default: number of CPU cores)
  -wu       Number of instances of transparent UDP proxy server (Default: number of CPU cores)
  -auto     Automatically setup iptables for transparent proxy (requires elevated privileges)
  -arpspoof Enable ARP spoof proxy for selected targets (Example: "targets 10.0.0.1,10.0.0.5-10,192.168.1.*,192.168.10.0/24;fullduplex false;debug true;interval 10s")
  -ndpspoof Enable NDP spoof proxy for selected targets (Example: "ra true;na true;targets fe80::3a1c:7bff:fe22:91a4;fullduplex false;debug true;interval 10s")
  -mark     Set mark for each packet sent through transparent proxy (Default: redirect 0, tproxy 100)
  -P        Comma separated list of ports to ignore when proxying traffic (Example: "22,80,443,9092")
  -dump     Dump iptables rules and other system settings generated by -auto flag
`

func root(args []string) error {
	conf := gohpts.Config{}
	flags := flag.NewFlagSet(app, flag.ExitOnError)
	flags.StringVar(&conf.AddrSOCKS, "s", addrSOCKS, "Address of SOCKS5 proxy server")
	flags.StringVar(
		&conf.User,
		"u",
		"",
		"User for SOCKS5 proxy authentication. This flag invokes prompt for password (not echoed to terminal)",
	)
	flags.StringVar(&conf.AddrHTTP, "l", addrHTTP, "Address of HTTP proxy server")
	flags.StringVar(
		&conf.ServerUser,
		"U",
		"",
		"User for HTTP proxy (basic auth). This flag invokes prompt for password (not echoed to terminal)",
	)
	flags.StringVar(&conf.CertFile, "c", "", "Path to certificate PEM encoded file")
	flags.StringVar(&conf.KeyFile, "k", "", "Path to private key PEM encoded file")
	flags.StringVar(
		&conf.ServerConfPath,
		"f",
		"",
		"Path to server configuration file in YAML format (overrides other proxy flags)",
	)
	flags.BoolVar(&conf.IPv6Enabled, "6", false, "Enable IPv6 support for TCP and UDP")
	flags.StringVar(&conf.Interface, "i", "", "Bind proxy to specific network interface")
	flags.BoolFunc("I", "Display list of network interfaces and exit", func(flagValue string) error {
		if err := network.DisplayInterfaces(false); err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", app, err)
			os.Exit(2)
		}
		os.Exit(0)
		return nil
	})
	daemon := flags.Bool("D", false, "Run as a daemon (provide -logfile to see logs)")
	if slices.Contains(gohpts.SupportedTProxyOS, runtime.GOOS) {
		flags.StringVar(&conf.TProxy, "t", "", "Address of transparent proxy server (it starts along with HTTP proxy server)")
		flags.StringVar(&conf.TProxyOnly, "T", "", "Address of transparent proxy server (no HTTP)")
		flags.StringVar(&conf.TProxyUDP, "Tu", "", "Address of transparent UDP proxy server")
		flags.Func("M", fmt.Sprintf("Transparent proxy mode: %s", gohpts.SupportedTProxyModes), func(flagValue string) error {
			if !slices.Contains(gohpts.SupportedTProxyModes, flagValue) {
				fmt.Fprintf(os.Stderr, "%s: %s is not supported (type '%s -h' for help)\n", app, flagValue, app)
				os.Exit(2)
			}
			conf.TProxyMode = flagValue
			return nil
		})
		flags.UintVar(
			&conf.TProxyWorkers,
			"w",
			0,
			"Number of instances of transparent proxy server (Default: number of CPU cores)",
		)
		flags.UintVar(
			&conf.TProxyUDPWorkers,
			"wu",
			0,
			"Number of instances of transparent UDP proxy server (Default: number of CPU cores)",
		)
		flags.BoolVar(
			&conf.Auto,
			"auto",
			false,
			"Automatically setup iptables for transparent proxy (requires elevated privileges)",
		)
		flags.UintVar(
			&conf.Mark,
			"mark",
			0,
			"Set mark for each packet sent through transparent proxy (Default: redirect 0, tproxy 100)",
		)
		flags.StringVar(
			&conf.ARPSpoof,
			"arpspoof",
			"",
			"Enable ARP spoof proxy for selected targets",
		)
		flags.StringVar(
			&conf.NDPSpoof,
			"ndpspoof",
			"",
			"Enable NDP spoof proxy for selected targets",
		)
		flags.StringVar(
			&conf.IgnoredPorts,
			"P",
			"",
			`Comma separated list of ports to ignore when proxying traffic (Example: "22,80,443,9092")`,
		)
		flags.BoolVar(
			&conf.Dump,
			"dump",
			false,
			"Dump iptables rules and other system settings generated by -auto flag",
		)
	}
	flags.StringVar(&conf.LogFilePath, "logfile", "", "Log file path (Default: stdout)")
	flags.BoolVar(&conf.Debug, "d", false, "Show logs in DEBUG mode")
	flags.BoolVar(&conf.JSON, "j", false, "Show logs in JSON format")
	flags.BoolVar(&conf.Sniff, "sniff", false, "Enable traffic sniffing for HTTP and TLS")
	flags.StringVar(&conf.SniffLogFile, "snifflog", "", "Sniffed traffic log file path (Default: the same as -logfile)")
	flags.StringVar(&conf.AddrPprof, "pprof", "", "Address of pprof server with profiling data")
	flags.BoolVar(&conf.NoColor, "nocolor", false, "Disable colored output for logs (no effect if -j flag specified)")
	flags.BoolVar(&conf.Body, "body", false, "Collect request and response body for HTTP traffic (credentials, tokens, etc)")
	flags.BoolFunc("v", "Show version and build information", func(flagValue string) error {
		fmt.Printf("%s (built for %s %s with %s)\n", gohpts.Version, runtime.GOOS, runtime.GOARCH, runtime.Version())
		os.Exit(0)
		return nil
	})

	flags.Usage = func() {
		fmt.Print(usagePrefix)
		if slices.Contains(gohpts.SupportedTProxyOS, runtime.GOOS) {
			fmt.Print(usageTproxy)
		}
	}

	if err := flags.Parse(args); err != nil {
		return err
	}
	seen := make(map[string]bool)
	flags.Visit(func(f *flag.Flag) { seen[f.Name] = true })
	if seen["t"] && seen["T"] {
		return fmt.Errorf("cannot specify both -t and -T flags")
	}
	if seen["t"] {
		if !seen["M"] {
			return fmt.Errorf("transparent proxy mode is not provided: -M flag")
		}
	}
	if seen["T"] {
		for _, da := range []string{"U", "c", "k", "l"} {
			if seen[da] {
				return fmt.Errorf("-T flag does not work with -U, -c, -k, -l flags")
			}
		}
		if !seen["M"] {
			return fmt.Errorf("transparent proxy mode is not provided: -M flag")
		}
	}
	if seen["Tu"] {
		if !seen["M"] {
			return fmt.Errorf("transparent proxy mode is not provided: -M flag")
		}
		if conf.TProxyMode != "tproxy" {
			return fmt.Errorf("transparent UDP proxy require tproxy mode")
		}
	}
	if seen["M"] {
		if !seen["t"] && !seen["T"] && !seen["Tu"] {
			return fmt.Errorf("transparent proxy mode requires -t, -T or -Tu flag")
		}
	}
	if seen["w"] {
		if !seen["t"] && !seen["T"] {
			return fmt.Errorf("-w requires -t, or -T flag")
		}
	}
	if seen["wu"] {
		if !seen["Tu"] {
			return fmt.Errorf("-wu requires -Tu flag")
		}
	}
	if seen["ndpspoof"] {
		if !seen["6"] {
			return fmt.Errorf("-ndpspoof requires -6 flag")
		}
	}
	if seen["mark"] {
		if !seen["t"] && !seen["T"] && !seen["Tu"] {
			return fmt.Errorf("-mark requires -t, -T or -Tu flag")
		}
	}
	if seen["P"] {
		if !seen["auto"] {
			return fmt.Errorf("-P requires -auto flag")
		}
	}
	if seen["dump"] {
		if !seen["auto"] {
			return fmt.Errorf("-dump requires -auto flag")
		}
	}
	if seen["f"] {
		for _, da := range []string{"s", "u", "U", "c", "k", "l", "i"} {
			if seen[da] {
				return fmt.Errorf("-f flag does not work with other proxy flags specified")
			}
		}
	}
	if seen["D"] {
		if seen["u"] || seen["U"] {
			return fmt.Errorf("-u and -U flags do not work in daemon mode")
		}
	}
	if seen["u"] {
		fmt.Print("SOCKS5 Password: ")
		bytepw, err := term.ReadPassword(int(os.Stdin.Fd()))
		if err != nil {
			return err
		}
		conf.Pass = string(bytepw)
		fmt.Print("\033[2K\r")
	}
	if seen["U"] {
		fmt.Print("HTTP Password: ")
		bytepw, err := term.ReadPassword(int(os.Stdin.Fd()))
		if err != nil {
			return err
		}
		conf.ServerPass = string(bytepw)
		fmt.Print("\033[2K\r")
	}
	if seen["snifflog"] {
		if !seen["sniff"] {
			return fmt.Errorf("-snifflog only works with -sniff flag")
		}
	}
	if seen["body"] {
		if !seen["sniff"] {
			return fmt.Errorf("-body only works with -sniff flag")
		}
	}

	if *daemon {
		if os.Getenv("GOHPTS_DAEMON") != "1" {
			env := os.Environ()
			files := [3]*os.File{}
			env = append(env, "GOHPTS_DAEMON=1")
			files[0], _ = os.Open(os.DevNull)
			files[1], _ = os.Open(os.DevNull)
			files[2], _ = os.Open(os.DevNull)
			attr := &os.ProcAttr{
				Files: []*os.File{
					files[0], // stdin
					files[1], // stdout
					files[2], // stderr
				},
				Dir: ".",
				Env: env,
			}
			path, err := os.Executable()
			if err != nil {
				return err
			}
			process, err := os.StartProcess(
				path,
				os.Args,
				attr,
			)
			if err != nil {
				return err
			}
			fmt.Printf("%s pid: %d\n", app, process.Pid)
			process.Release()
			os.Exit(0)
		}
	}
	p := gohpts.New(&conf)
	p.Run()
	return nil
}
